---
version: '2'
services:
  postfix:
    image: devanalabs/lemonemail-dev.postfix
    container_name: postfix
    ports:
      - "25:25"
      - "465:465"
    networks:
      app_net:
        ipv4_address: 172.19.25.3
    env_file:
          - variables.env
    links: [dovecot, spam, mysql, dkim]

  dovecot:
    image: devanalabs/lemonemail-dev.dovecot
    container_name: dovecot
    ports:
      - "993:993"
      - "143:143"
      - "24:24"
    networks:
      app_net:
        ipv4_address: 172.19.25.4
    env_file:
          - variables.env
    links: [mysql]

  spam:
      image: devanalabs/lemonemail-dev.spam
      container_name: spam
      ports:
        - "10024:10024"
      networks:
        app_net:
          ipv4_address: 172.19.25.5
      env_file:
            - variables.env
      links: [dovecot, mysql]

  mysql:
        image: devanalabs/lemonemail-dev.mysql
        container_name: mysql
        ports:
          - "3306:3306"
        networks:
          app_net:
            ipv4_address: 172.19.25.6
        env_file:
              - variables.env
  dkim:
        image: devanalabs/lemonemail-dev.dkim
        container_name: dkim
        ports:
          - "8891:8891"
        networks:
          app_net:
            ipv4_address: 172.19.25.7
        env_file:
              - variables.env

networks:
  app_net:
   driver: bridge
   ipam:
      driver: default
      config:
       - subnet: 172.19.25.0/24
         gateway: 172.19.25.1
